model_family: zephyr-7b-beta
model_path: wmdp/model
save_dir: wmdp/base/${model_family}/${forget_loss}_${lr}_${split}_${num_epochs}_${weight_decay}_${beta}and${npo_coeff}

LoRA:
  r: 0
  alpha: 32
  dropout: 0.05

lr: 4e-6
split: wmdp
retain_set: wmdp
batch_size: 4
gradient_accumulation_steps: 1
num_epochs: 10
forget_loss: simnpo_grad_diff

npo_coeff: 5.0
grad_diff_coeff: 1.0
KL_coeff: 1.0
ref_policy: fine_tuned
beta: 5.5
weight_decay: 0.0
gamma: 0.0
seed: 42
run_index: 1
overwrite_dir: true
eval_steps: steps_per_epoch
warmup_steps: steps_per_epoch

save_steps: 250
#data_path: locuslab/TOFU
save_model: true
eval_while_train: false
eval_only: false

eval:
  retain_result: data/${..retain_set}_llama_wd0.01/eval_results/ds_size300/eval_log_aggregated.json
  model_path: ${..model_path}
  model_family: ${..model_family}
  save_dir: ${..save_dir}
  aggr_save_dir: ${..aggr_save_dir}
  data_path: [locuslab/TOFU, locuslab/TOFU, locuslab/TOFU, locuslab/TOFU]
  split: ${..split}_perturbed
  split_list:
    - retain_perturbed
    - real_authors_perturbed
    - world_facts_perturbed
    - ${split}

  eval_task: [eval_log, eval_real_author_wo_options, eval_real_world_wo_options, eval_log_forget]
  question_key: [question, question, question, question]
  answer_key: [answer, answer, answer, answer]
  base_answer_key: [paraphrased_answer, answer, answer, paraphrased_answer]
  perturbed_answer_key: [perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer]

  generation:
    max_length: 200
    max_new_tokens: null

  save_generated_text: true

  ds_size: 300

  overwrite: true
  use_pretrained: false

  batch_size: 30
